services:
  db1:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=questionDb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=tj330'
    ports:
      - '5432:5432'
  db2:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=quizDb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=tj330'
    ports:
      - '5433:5432'
